name: Secret Scanning

on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        with:
          args: --redact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}